#!/bin/bash
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME"/doom
mkdir -p "$XDG_CONFIG_HOME"/nix

ln -sf "$PWD/packages.el" "$XDG_CONFIG_HOME"/doom/packages.el
ln -sf "$PWD/config.el" "$XDG_CONFIG_HOME"/doom/config.el
ln -sf "$PWD/init.el" "$XDG_CONFIG_HOME/"doom/init.el
ln -sf "$PWD/nix.conf" "$XDG_CONFIG_HOME"/nix/nix.conf

#nix-env -iA

# install doom emacs
git clone https://github.com/hlissner/doom-emacs ~/.config/emacs
