#!/bin/bash
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME"/nixpkgs
mkdir -p "$XDG_CONFIG_HOME"/doom

#ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
#ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix
ln -sf "$PWD/packages.el" "$XDG_CONFIG_HOME"/doom/packages.el
ln -sf "$PWD/config.el" "$XDG_CONFIG_HOME"/doom/config.el
ln -sf "$PWD/init.el" "$XDG_CONFIG_HOME/"doom/init.el

# install Nix packages from config.nix
nix-env -iA nixpkgs.myPackages

# install doom emacs
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
